version: 1.0.{build}
build:
  verbosity: minimal
  project: Foq.sln
test:
  assemblies:
    - Tests.FSharp.dll
    - Tests.FSharp.Linq.dll
    - Tests.VisualBasic.dll
    - Tests.CSharp.dll
    - Examples.dll